### ISSUE TITLE
Run command 'yarn start' error

### ISSUE THREAD

**Issue by wangdemon** [screego/server#100]
When I compile the code, I go to ‘yarn start’ command, there's a mistake
![img](https://user-images.githubusercontent.com/20681339/123618662-fed4e500-d83a-11eb-8249-9f88fb9c0582.png)

**Comment by jmattheis** [comment]
You need to start the backend too -> https://screego.net/#/development?id=backend

**Comment by wangdemon** [comment]
I already start the backend
![img2](https://user-images.githubusercontent.com/20681339/123619813-237d8c80-d83c-11eb-989b-01a70567cfbd.png)

**Comment by jmattheis** [comment]
they must both be started, then the error shouldn't occur. (if you've started the backend after the ui, then the error message is old and not relevant anymore)

**Comment by wangdemon** [comment]
I started the backend， and then enter ui directory, started frontend. The same error occurred.

**Comment by jmattheis** [comment]
You are using screego with tls, the devmode expects you to use http, so disable SCREEGO_SERVER_TLS.

**Comment by wangdemon** [comment]
Thank you very much. The problem has been solved.
