### ISSUE TITLE
[feature request] Allow external STUN/TURN

### ISSUE THREAD

**Issue by aanno** [screego/server#101]
Would it be possible to extend screego to allow for an external STUN/TURN server, e.g. https://github.com/coturn/coturn ?

**Comment by jmattheis** [comment]
This is already possible, see config.
https://github.com/screego/server/blob/aeb55c7387f27de252aefbee0b45f23d7e0ff645/screego.config.example#L39-L52

**Comment by aanno** [comment]
Oh, thanks! I missed that.
