### ISSUE TITLE
Remote cursor

### ISSUE THREAD

**Issue by davidnmbond** [screego/server#108]
Screego is absolutely great and we are using it for pair development.  Thanks for this!

What would make it absolutely perfect for our purposes would be to show the remote cursor.  Here's the ideal behaviour:

- All connected users' cursor positions are captured by the remote browser.
- Each is given a separate colour, ideally from a pastel colour palette: e.g. https://colorhunt.co/palettes/pastel
- When remote users have not moved the cursor for more than (e.g.) 2 seconds, their cursor disappears
- All participants can see all other participants' cursors
- Each cursor has the remote users' name against it

**Comment by hydra** [comment]
This is pretty essential for pair-programming sessions.

**Comment by coreequip** [comment]
The idea sounds great but with native browser technology it's impossible to achieve. The only way would be that the presenter has his own video stream on a second screen and there is the remote cursor shown. The problem is that a browser can't show a transparent "overlay" an a screen.

**Comment by jmattheis** [comment]
I think it would be useful, but without a native application it won't have good user experience.
