### ISSUE TITLE
Center video in display mode: original

### ISSUE THREAD

**Issue by DennisBecker** [screego/server#109]
Changing the display mode to original the video will stay in the upper left corner, which looks weird. I fix that by myself with a snippet of CSS but this might be added as default for this mode.

```
<div class="jss41" style="
    display: flex;
    align-items: center;
    justify-content: center;">
        <video class="jss33"></video>
        <div class="jss31"></div>
</div>
```

**Comment by jmattheis** [comment]
Sure thing, would you like to create a PR for this? You'd probably have to create a new css class [here](https://github.com/screego/server/blob/master/ui/src/Room.tsx#L509) and append the added class [here](https://github.com/screego/server/blob/master/ui/src/Room.tsx#L205)

**Comment by DennisBecker** [comment]
I treid it but I cannot run the screego server on my WIndows OS with Docker for Windows and WSL2 because I cannot build the server. But from my tests in the browser, I have to extend the CSS snippet to the videoContainer class. I will add this and open a PR.
