### ISSUE TITLE
Hash command should output password prompt to stderr to allow redirecting result to file

### ISSUE THREAD

**Issue by skyhisi** [screego/server#12]
To be able to use a command like `screego hash --name foo >>users`, it would be useful to make the password prompt be output to stderr rather than stdout.

I think the line to change is this one:

https://github.com/screego/server/blob/a14762d37f23a55c81245de53b030c8ca11ad82e/cmd/hash.go#L28

**Comment by jmattheis** [comment]
Good idea!
