### ISSUE TITLE
Another user cannot see the video stream after entering the room

### ISSUE THREAD

**Issue by wangdemon** [screego/server#124]
I deploy the screego program on my Cloud Servers, as shown in the figure  below
![1](https://user-images.githubusercontent.com/20681339/162248621-de918a95-04c6-47ca-9cf1-53cc3dabb6f0.png)
One of my computers connects to the home broadband, I uses Micrsoft Edge browser to access the IP listened by the screego, creates a room,  and starts push stream
![2](https://user-images.githubusercontent.com/20681339/162249486-4eaa30eb-00e0-4367-ae6b-f8d29f55b61f.png)
My other computer connects to the mobile network hotspot and visits the room shown above. but I can't see the streaming screen
![3](https://user-images.githubusercontent.com/20681339/162249952-a7137c38-6245-4b1e-9ba4-c5e0ab3b602f.png)

**Comment by jmattheis** [comment]
Check every point on https://screego.net/#/faq?id=stream-doesnt-load

**Comment by wangdemon** [comment]
I may not be very clear. Well, I mean，My two computer in the same LAN, I can see the video stream. If my two computer not in the LAN, I can't see the video stream.The Scrego program was deploy in Cloud server.

**Comment by jmattheis** [comment]
If that's the case, then check every point on https://screego.net/#/faq?id=stream-doesnt-load

**Comment by wangdemon** [comment]
Now, both my computers can see the video stream.I don't know why, but I'm talking about the solution.
(1) If the computer connects to the mobile network hotspot, it won't display the video stream. However, when the mobile phone uses the mobile network, it will be dispaly the video stream.
(2) It must use a certified certificate to see the video stream.
There is another problem, after entering the room, I don't know why, it's easy to disconnect.
Thank the author for his selfless dedication.
