### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by wangdemon** [screego/server#125]
I using screego 1.6.2 version,There is some problems:
(1) Android phones can see the video stream. Apple phones can't see the video stream. In very few cases, it can display the video stream
![1](https://user-images.githubusercontent.com/20681339/162602640-68bc467a-55a3-45c2-9a34-8777ff8ab1fb.jpeg)

(2)In ubuntu 18.4, using Firefox browers(92.0 version) push stream,after ten minutes , the computer will become very stuck. and closing the streaming page, the computer will become smooth again

**Comment by jmattheis** [comment]
1. apple phone no stream -> https://github.com/screego/server/issues/55 Screego does not support apple phones.
2. Does the problem also occur with google-chrome / chromium?

**Comment by wangdemon** [comment]
1 Screego support apple phones. Because I have run successfully, you can see the following figure. But only run successfully once.
![2](https://user-images.githubusercontent.com/20681339/163914226-a14c2fd2-00f2-4a6b-91c9-adffe8b577e8.gif)
After ios14.3 version, webrtc is supported.
2 Google Chrome didn't occur stuck

**Comment by wangdemon** [comment]
![动画1](https://user-images.githubusercontent.com/20681339/163914798-2d0b0d07-5543-4c64-8927-ccd57de458bd.gif)

**Comment by wangdemon** [comment]
https://webkit.org/blog/11353/mediarecorder-api/
![1](https://user-images.githubusercontent.com/20681339/163928281-2a27c652-1421-421e-829f-d1a588c9c41d.png)

**Comment by wangdemon** [comment]
Today, I tested the screego program with my Apple phone, Accidentally found that when there are two streaming sources in a room, click the video small window, which will display the video stream.As shown in the figure below
![4](https://user-images.githubusercontent.com/20681339/163938352-e1d49384-ca47-423a-9dc7-6f743431f377.png)

**Comment by jmattheis** [comment]
so everything works now?

**Comment by wangdemon** [comment]
how should I put it，There are still some small problems.
1 If you use Apple mobile phone to access the video stream, there are two users push the stream to display the video stream. A user push stream, it cannot be seen.
2 In China(My country), I try to Mobile sim card and Unicom sim card to access the video stream，only mobile sim cards can display video stream

**Comment by jmattheis** [comment]
I don't understand your first point. I cannot really debug your second point as I don't have access to these sim cards.

**Comment by wangdemon** [comment]
1 Sorry, forgive me for my poor English and can't express my thoughts. Look at the video below, you can understand what I want to express.

https://user-images.githubusercontent.com/20681339/164416449-7bdf71eb-1495-46c9-8040-eed8f66317db.mp4

2 The problem has been solved. It should be caused by the firewall. Using the TURN server, it display the video stream

**Comment by jmattheis** [comment]
Yeah, there is probably something wrong with the autoplay of videos on ios devices, I don't have an ios device thus I cannot debug this.

**Comment by wangdemon** [comment]
Thanks for your selfless dedication
