### ISSUE TITLE
could not start turn server

### ISSUE THREAD

**Issue by Kirides** [screego/server#13]
trying to run it on windows leads to the following:
`FTL could not start turn server error="turn: RelayAddress must be valid IP to use RelayAddressGeneratorStatic"`

```
> set SCREEGO_EXTERNAL_IP=217.X.X.249
> screego.exe serve
```

```
2020-10-07T10:42:16+02:00 INF SCREEGO_SECRET unset, user logins will be invalidated on restart
2020-10-07T10:42:16+02:00 INF Users file not specified
2020-10-07T10:42:16+02:00 FTL could not start turn server error="turn: RelayAddress must be valid IP to use RelayAddressGeneratorStatic"
```

**Comment by jmattheis** [comment]
Are you sure, that you've provided a valid ip?

**Comment by Kirides** [comment]
Well, i went to https://myip.is and put that ip in there.
Thats as external as it gets.

i even forwarded the ports `3478` & `8080`

**Comment by jiqing112** [comment]
same question

**Comment by jmattheis** [comment]
@jiqing112 Can you try out the newest version?

**Comment by jiqing112** [comment]
> @jiqing112 Can you try out the newest version?

Thank you for your reply. I just said it has been solved

**Comment by jiqing112** [comment]
> @jiqing112 Can you try out the newest version?

The reason is not clear. 

It seems that the configuration file is not found, although I have created a new screego.config file.

I built a new one screego.config , write the configuration, and then run successfully

Thank you for your greetings. The problem has been solved. Sorry to disturb you

**Comment by jmattheis** [comment]
Alright, nice to hear that it is solved (:.

**Comment by jiqing112** [comment]
I know why. Oh My stupid mistake
I'm used to using the "screen" command. 
The configuration file for this project is called “ screego.config”， I got it “screengo.config”
