### ISSUE TITLE
How do I build manually?

### ISSUE THREAD

**Issue by AIndoria** [screego/server#130]
Hello,

I'm having several issues building both the final step, as well as teh docker image from the docker file. I'm more familiar with JS/TS than I am with Go.

I've followed the steps at https://screego.net/#/development?id=build

Everything works except when I get to 

```
CGO_ENABLED=0 go build \
  -ldflags '-s -w -X main.version=`git describe --tags HEAD` -X main.mode=Prod' \
  -buildmode=pie -trimpath -tags 'netgo osusergo' main.go
```

This results in a 

![image](https://user-images.githubusercontent.com/8932732/176999733-a69bd0f6-ab9f-44ea-8a17-310bb8f7a2b0.png)

Further, while building a docker image 'works,' but running it ultimately results in

![image](https://user-images.githubusercontent.com/8932732/176999871-eb863d51-f59a-463c-9363-18c6687c1c55.png)

Building for other architectures (arm64 for example) give an exec error when done via buildx, which is a whole nother mess but I'd like to get this sorted out for now if possible. Thank you.

**Comment by jmattheis** [comment]
I've updated the docs, use:
```bash
$ go build -ldflags "-X main.version=$(git describe --tags HEAD) -X main.mode=Prod" -o screego ./main.go
```
Building the Dockerfile requires a built screego binary.

**Comment by AIndoria** [comment]
> ```shell
> go build -ldflags "-X main.version=$(git describe --tags HEAD) -X main.mode=prod" -o screego ./main.go
> ```

Thank you for this. So,

As described in https://github.com/screego/server/issues/114, I can get the screego binary to be placed in the root directory by just doing `go build -o screego .` or in this instance, the above command you listed. That too is fine.

However, building an image using docker still 'fails.' IT will 'work' but it will cause the above mentioned 

`exec /screego: no such file or directory`

**Comment by jmattheis** [comment]
If you want to use it with the docker image you've to create a statically linked binary, because the docker image doesn't contain libc
```
CGO_ENABLED=0 go build -ldflags "-X main.version=`git describe --tags HEAD` -X main.mode=Prod" --tags 'netgo os' -o screego  main.go
```

**Comment by AIndoria** [comment]
Interesting. That worked, ty. How do I serve the UI though? This seem to only serve the server in the Dockerfile. Do I have to add instructions in the dockerfile to copy over the src and public pages and do a yarn start?

**Comment by jmattheis** [comment]
The UI will be embedded into the binary. You've to build the UI before building the binary.
