### ISSUE TITLE
Possible to add support for system audio?

### ISSUE THREAD

**Issue by SirCypher** [screego/server#131]
Hi!
Thanks for this neat little project! It's working very well so far!

With the "screensy" project I can select "system audio" when Chrome offers the screenshare menu.
Is it possible to add support for sharing system audio with screego too?

(Sidenote: Chromium-based browsers support sharing system audio while sharing the screen. Unfortunately Firefox does not support this yet.)

Thanks a lot and best regards

**Comment by jmattheis** [comment]
Duplicate https://github.com/screego/server/issues/68#issuecomment-767734409
