### ISSUE TITLE
Will you consider adding support for sound in the future?

### ISSUE THREAD

**Issue by snail2sky** [screego/server#134]
## question
- It is true that remote presentation can be done at present, but it seems that the frame rate is not very high, and the screen projection through screego will cause lag
- At present, there is no support for sound. In my impression, H5 seems to be able to share sound (similar technology was used through an online interview at that time)

**Comment by snail2sky** [comment]
It works really well so far, thanks

**Comment by jmattheis** [comment]
> It is true that remote presentation can be done at present, but it seems that the frame rate is not very high, and the screen projection through screego will cause lag

You can change the video codec in the setting, using the browser default may give you a higher frame rate but with more artifacts in the video stream.

> At present, there is no support for sound. In my impression, H5 seems to be able to share sound (similar technology was used through an online interview at that time)

No, there won't be sound support for screego.

**Comment by snail2sky** [comment]
> > It is true that remote presentation can be done at present, but it seems that the frame rate is not very high, and the screen projection through screego will cause lag
> 
> You can change the video codec in the setting, using the browser default may give you a higher frame rate but with more artifacts in the video stream.
> 
> > At present, there is no support for sound. In my impression, H5 seems to be able to share sound (similar technology was used through an online interview at that time)
> 
> No, there won't be sound support in screego.

Ok, that's enough, thank you so much!

**Comment by snail2sky** [comment]
Ok, that's enough, thank you so much!
