### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by wangdemon** [screego/server#141]
Google Browser push stream, and using 3 to 4 tab windows to play the video stream, The CPU usage is high, and then when Google Chrome plays videos, the CPU usage is low. Watching the video below.
(1) Google Browser push stream, and play the video stream
[push stream video](https://youtu.be/6vxEXQLyE1Q)
(2) Goolge browser play local video
[play local video](https://youtu.be/20yj-c-ZHWw)

**Comment by jmattheis** [comment]
Screen sharing is much more expensive than viewing videos. Screego doesn't limit the resolution or frame rate, which could potentially improve performance. Also, it was built for the best quality, so it all works as intended.
