### ISSUE TITLE
IIS reverse proxy

### ISSUE THREAD

**Issue by piratov** [screego/server#143]
Unable to enter the room without specifying the port
It enters without a port but does not let it into the room

LOG debug
Websocket upgrade error="websocket: request origin not allowed by Upgrader.CheckOrigin"

![image](https://user-images.githubusercontent.com/17856390/202895554-b5ca42e4-1441-4aea-9503-8a115e91043a.png)
![image](https://user-images.githubusercontent.com/17856390/202895783-4cce82a9-8bda-47ac-a18d-d3afa617b85d.png)

web.config
`<rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule2" stopProcessing="true">
                    <match url="(.*)" />
                    <conditions>
                        <add input="{CACHE_URL}" pattern="^(https?)://" />
                    </conditions>
                    <action type="Rewrite" url="{C:1}://{HTTP_HOST}:5050/{R:1}" />
                </rule>
            </rules>
        </rewrite>`

**Comment by jmattheis** [comment]
Try adding the your origin to
```
# Defines origins that will be allowed to access Screego (HTTP + WebSocket)
# The default value is sufficient for most use-cases.
# Example Value: https://screego.net,https://sub.gotify.net
SCREEGO_CORS_ALLOWED_ORIGINS=
```
See https://screego.net/#/config

**Comment by piratov** [comment]
thank you all solved)
