### ISSUE TITLE
TURN server gives Allocate-request error in logs when trying to screenshare

### ISSUE THREAD

**Issue by tprepper** [screego/server#145]
When a participant tries to screenshare, this message gets spammed in the logs. Why is that? I have 3478/tcp and 3478/udp open and forwarded, I tried adding user accounts because of the "no such user exists" thing, but nothing seems to be fixing it.
```
turn ERROR: 2023/01/05 05:50:19 error when handling datagram: failed to handle Allocate-request from xxx.xxx.xxx.xxx:50639: no such user exists cerXXXXXXXXXXXhost (not sure if I should be blanking this out)
```

I have checked the FAQ https://screego.net/#/faq
- I am using HTTPS to access Screego
- `SCREEGO_EXTERNAL_IP` is set to my external IP
- Under the room id it says it's using TURN for NAT traversal
- My browser doesn't block WebRTC as screensharing works on other screensharing webapps
- I have reverse proxied 5050 to 443 at the screen subdomain, 3478 udp and tcp is open and the range 50000-55000 is open and set in the configuration. 

I have also set the `SCREEGO_TRUST_PROXY_HEADERS` to true

**Comment by tprepper** [comment]
I am on the same network and IP as the machine that runs Screego, if that matters.

**Comment by jmattheis** [comment]
Could you try enabling debug logging via
```ini
SCREEGO_LOG_LEVEL=debug
```
are you setting the X-Real-Ip header in your reverse proxy like it is described in the trust proxy headers setting?
```ini
# If reverse proxy headers should be trusted.
# Screego uses ip whitelisting for authentication
# of TURN connections. When behind a proxy the ip is always the proxy server.
# To still allow whitelisting this setting must be enabled and
# the `X-Real-Ip` header must be set by the reverse proxy.
SCREEGO_TRUST_PROXY_HEADERS=false
```
You could try disabling `SCREEGO_TURN_STRICT_AUTH=false` if the `X-Real-Ip` header is set but doesn't work.
