### ISSUE TITLE
Firefox: RTCRtpSender is not defined

### ISSUE THREAD

**Issue by ostrolucky** [screego/server#148]
In Firefox, on https://app.screego.net/ I'm getting blank page with this in console:

```
Uncaught ReferenceError: RTCRtpSender is not defined
    km SettingDialog.tsx:30
    <anonymous> SettingDialog.tsx:36
    <anonymous> index.tsx:96
    <anonymous> index.tsx:96
```

Firefox version: 111.0b8 (64-bit
Platform: aarch64-darwin

Other WebRTC demos that I tried work. 
Works in Google Chrome.

**Comment by jmattheis** [comment]
Weird, https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender describes that it's available. I tried the Firefox beta on amd64 arch, but this seems to work fine.

I've deployed a fix on https://app.screego.net could you check out, if it now works for you? You maybe have to clear your cache.

**Comment by ostrolucky** [comment]
Fix didn't do anything, however I've digged deeper and identified the problem! It was https://addons.mozilla.org/en-US/firefox/addon/hide-me-vpn-free-proxy/. I'll report the issue to hide.me folks. Sorry for unnecessary alert.
