### ISSUE TITLE
Require login to create room

### ISSUE THREAD

**Issue by ibLeDy** [screego/server#15]

**Comment by jmattheis** [comment]
See https://screego.net/#/config
```ini
# Defines when a user login is required
# Possible values:
#   all: User login is always required
#   turn: User login is required for TURN connections
#   none: User login is never required
SCREEGO_AUTH_MODE=turn
```

**Comment by ibLeDy** [comment]
I saw that, but a guest can still create a room without authentication using `stun`, so maybe what i'm suggesting is the option to ONLY use `turn`.

**Comment by jmattheis** [comment]
When setting this option to `all`, the UI looks like this. There is no way to create a room without login:
![image](https://user-images.githubusercontent.com/14895212/95349396-927e1400-08ae-11eb-9906-a97216263ac6.png)

**Comment by ibLeDy** [comment]
Yes, but then no guest can join a room if i'm not mistaken.

**Comment by jmattheis** [comment]
The authmode is only for room creation, everyone can join.

**Comment by ibLeDy** [comment]
Oh okay, i'm sorry for wasting your time then

**Comment by jmattheis** [comment]
No problem (:.
