### ISSUE TITLE
Config for Default Room Name

### ISSUE THREAD

**Issue by Aeyk** [screego/server#151]
Instead of generating a number random room name, it would be useful to have a config setting setting the default room name. In my case, I am not expecting anyone to create more than one group.

It's really fast, and the documentation and examples are very easy to follow so thank you.

**Comment by jmattheis** [comment]
I don't think many users will need. As an alternative, you could bookmark a link including a room name like https://app.screego.net/?room=prefilled if the room doesn't exist, it will prefill the room name. You can also append `&create=true` to create the room if it doesn't exist already.

**Comment by Aeyk** [comment]
Thanks for the create tip, that's useful. I have set it to add the
room name via NGINX as a reverse proxy, so I can also have it
&create=true it automatically there too.
