### ISSUE TITLE
Unchecking 'Close Room after you leave' has no effect

### ISSUE THREAD

**Issue by bielej** [screego/server#16]
**Steps to reproduce:**
1. Visit your Screego instance
2. Set a room name (ie. `test`)
3. Uncheck _Close Room after you leave_
4. Click _Create room_
5. After creating the room, close the browser tab (or close the browser)
6. Reopen closed tab
7. See the error `room with id test does not exist`

**Expected behavior:**
Room should remain available after leaving the site.

**Version:**
```
screego version 1.0.1; screego/server@fa388f6e59401059530fae9d6d15da809fe2abb7
```

**Comment by jmattheis** [comment]
A room will always be closed when there are no users in it. Close room after you leave is an extra setting to close the room even if there are members left.

**Comment by bielej** [comment]
Understood.
