### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by dotNetCory** [screego/server#164]
Just a quick one, I believe there might be a mistake on the page
https://screego.net/#/install

When following the guide for not using the host network mode, it gives a range of ports, reading 

5000-5100:5000-5200

Which leave 100 ports out of range. On my personal I've expanded it to the 5000-5200, but it would be nice to know if I can shrink that range

**Comment by jmattheis** [comment]
Yeah that's a typo. You can shrink the range.  50 ports in the range are probably enough,  but that depends on how many clients will receive the shared video.
