### ISSUE TITLE
mediaDevices undefined

### ISSUE THREAD

**Issue by youliliang** [screego/server#166]
use     docker run --net=host -e SCREEGO_EXTERNAL_IP=EXTERNALIP ghcr.io/screego/server:1.10.0      pic.1
mediaDevices undefined???     pic.2
![Uploading Snipaste_2023-08-21_16-28-33.png…]()
![Uploading Snipaste_2023-08-21_16-27-21.png…]()

**Comment by jmattheis** [comment]
See https://github.com/screego/server/issues/78
