### ISSUE TITLE
Static or live screen sharing?

### ISSUE THREAD

**Issue by OrionRandD** [screego/server#168]
Does this program just static share your screen or live share.
E.g.: When sharing, say, Emacs, the other person sees what I am doing in Emacs? Or it is just an static image of Emacs...

**Comment by jmattheis** [comment]
Live screen sharing. You can try it yourself on the demo instance available at https://app.screego.net/ open the same room in two browser tabs.

**Comment by OrionRandD** [comment]
> Live screen sharing. You can try it yourself on the demo instance available at https://app.screego.net/ open the same room in two browser tabs.

All right! So, it is possible to use, say, Mumble <https://www.mumble.info/downloads/>, as a chat tool between a person, or some people, in a room and use screego as a sharing screen... I think... Am I right?

**Comment by jmattheis** [comment]
Yes.
