### ISSUE TITLE
Cannot share Dev-C++ IDE window

### ISSUE THREAD

**Issue by xiaguoxin** [screego/server#172]
I want to share Dev-C++ IDE window with others, but in screego select window, the Dev-C++ IDE is all black, and cannot be shared correctly.

**Comment by jmattheis** [comment]
Screego uses the native browser apis, if they cannot share a specific window, then there is nothing screego can do about this.

Other browser based screen sharing apps have the same problem: https://support.google.com/meet/thread/125017286/google-meet-share-blank-screen-on-some-application?hl=en
