### ISSUE TITLE
"No stream available"

### ISSUE THREAD

**Issue by afunworm** [screego/server#174]
Hello.

I tested the public demo instance and verified that the public demo works. I then went ahead and deployed my own Docker version of it:

```bash
docker run -d --restart always --name screego \
    -e SCREEGO_EXTERNAL_IP=MY_EXTER_IP_ADDRESS \
    -e SCREEGO_TURN_PORT_RANGE=50000:50200 \
    -p 5050:5050 \
    -p 3478:3478 \
    -p 50000-50200:50000-50200/udp \
    screego/server:1.10.2
```

I can successfully visit localhost:5050 as well as mypublicdomain.com:5050 to see the website. I was able to log in. However, when I start streaming from one device to another, it's just all black. "No stream available."

Firewall on the machine that's hosted ScreeGo is off. NAT fowarding forwards 5050, 3478 and 50000-50200 to the machine properly.

I am not sure what other steps I should take.

Please advice.

**Comment by jmattheis** [comment]
Does it work with https://app.screego.net/ ?

**Comment by afunworm** [comment]
> Does it work with https://app.screego.net/ ? And are there any error messages in the browser console?

Yes! The public demo instance works perfectly.

There's no errror. From the viewer side, this is the log:

![image](https://github.com/screego/server/assets/5475479/07887f05-1fcf-46c3-9a7c-14e1272cbf1e)

Empty console on the streamer's side.

Screego was installed using Docker on Ubuntu 22.04.

**Comment by jmattheis** [comment]
Would you share your public url? You can do it privately via the email on my GitHub profile.

**Comment by afunworm** [comment]
> Would you share your public url? You can do it privately via the email on my GitHub profile.

Emailed! Thank you.

**Comment by jmattheis** [comment]
Could you enable `SCREEGO_LOG_LEVEL=debug` and try using screego and paste the output here? Could you also send me credentials for logging into your instance? The normal connections seems to work fine for me.

Does screen sharing on the same device to the same device works for both your devices?

**Comment by afunworm** [comment]
> Could you enable `SCREEGO_LOG_LEVEL=debug` and try using screego and paste the output here? Could you also send me credentials for logging into your instance? The normal connections seems to work fine for me.
> 
> Does screen sharing on the same device to the same device works for both your devices?
> 
> Which browser are you using? If not chrome please try it with chrome or a chromium browser on both devices.

Hi.

Do I just pass in the environment when starting Docker?

Thanks.

**Comment by jmattheis** [comment]
Yes, similar to the other settings like `SCREEGO_EXTERNAL_IP=MY_EXTER_IP_ADDRESS`
