### ISSUE TITLE
Is there no audio for sharing?

### ISSUE THREAD

**Issue by DelbertTony** [screego/server#184]

**Comment by BroderPeters** [comment]
Most recent updates should be here I think: https://github.com/screego/server/pull/181 + https://github.com/screego/server/pull/181#pullrequestreview-2121422212

**Comment by AdelleBernal** [comment]
Do I understand correctly that there is audio support? I can't seem to see it when streaming youtube videos.

**Comment by jmattheis** [comment]
No, there is an open pull request but it's not included in the project yet.
