### ISSUE TITLE
docker config and mediaDevices undefined?

### ISSUE THREAD

**Issue by fightersabo** [screego/server#187]
hi
i have two problems docker config and Could not start presentation. (mediaDevices undefined) Are you using https?

**Comment by jmattheis** [comment]
Are you using https?

**Comment by fightersabo** [comment]
yes im using https

**Comment by jmattheis** [comment]
Screego requires https.

**Comment by fightersabo** [comment]
how can i run https via docker

**Comment by jmattheis** [comment]
Either configure a reverse proxy with tls or set these config values:
```
# If TLS should be enabled for HTTP requests. Screego requires TLS,
# you either have to enable this setting or serve TLS via a reverse proxy.
SCREEGO_SERVER_TLS=false
# The TLS cert file (only needed if TLS is enabled)
SCREEGO_TLS_CERT_FILE=
# The TLS key file (only needed if TLS is enabled)
SCREEGO_TLS_KEY_FILE=
```
https://screego.net/#/config

**Comment by fightersabo** [comment]
i have no idea can your crate  guide line/

**Comment by jmattheis** [comment]
You could use traefik: https://doc.traefik.io/traefik/user-guides/docker-compose/acme-tls/ or create a self signed certificate and configure it in traefik. There already should be a lot of guides about this on the internet as almost every web application needs this.
