### ISSUE TITLE
https://screego.net/ (docs instance) not loading.

### ISSUE THREAD

**Issue by deafmute1** [screego/server#188]
Screego.net endlessly shows loading circle, never loads. Tried it on my usual firefox as well as a plain google chrome instance with no extensions, no difference. Is there any other source for documentation?

**Comment by jmattheis** [comment]
Could you check your browser console for errors and post them here? You can find the raw docs here https://github.com/screego/server/tree/master/docs

**Comment by deafmute1** [comment]
Its working now, closing unless i hit similar errors.
