### ISSUE TITLE
Question - Potential for chat implementation ?

### ISSUE THREAD

**Issue by HomelabHaven** [screego/server#194]
Hello there,

first of all I truly appreciate the screego server project as it is the only alternative to discord screen-sharing that is self-hosted and viable in my opinion.
Thank you. :)

Out of curiosity: Is a per-room chat implementation planned in the future?

Kind regards

**Comment by jmattheis** [comment]
Glad you like it. It's not planned and really unlikely that it will be implemented. I try to keep screego as simple as possible while satisfying the goal "screen sharing for developers".

Every feature adds complexity that I don't want and there are already projects that support text + voice chat like Jitsi or bigbluebutton. I don't want to compete with them, I just want my screensharing crisp and without latency (:.

**Comment by HomelabHaven** [comment]
My pleasure.
The sponsoring is well deserved. :)

I totally understand the minimization of complexity which usually ends up in "dependency hell" if you don't write most of the code yourself.
A combination of TeamSpeak3 and Screego fulfill all of my communication needs with my friends whilst gaming. ^^

**Comment by jmattheis** [comment]
I'll close this issue then, as it's not planned.
