### ISSUE TITLE
MacOS Safari browser screen sharing problem

### ISSUE THREAD

**Issue by ifoyil** [screego/server#198]
Hello,

macOS Sonoma 14.6.1 Safari browser doesn't share screen anymore it has like that message as below

"Could not start presentation. (getDisplayMedia error). NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission"

Screego version 1.10.5

**Comment by jmattheis** [comment]
When did it stopped working? With which macOS / Safari version did it work? I don't have an Apple device, so It's likely I can't solve this problem.
