### ISSUE TITLE
Option to lock rooms

### ISSUE THREAD

**Issue by no-one** [screego/server#199]
Since a login is never required to enter a room but only to create it, a complex room ID is the only way to prevent unwanted persons from joining. Would it be possible to add an option to lock rooms (could then be used as soon as everyone who is expected is present)? Then you could use shorter, "more logical" room IDs and still be sure that nobody enters the room unexpectedly.

Oh and thanks for this useful software!

**Comment by jmattheis** [comment]
Possible yes, but I think implementing https://github.com/screego/server/issues/107 should cover more use-cases.
