### ISSUE TITLE
WSS different port

### ISSUE THREAD

**Issue by idanless** [screego/server#200]
Hi

need a help 
 
I bind the Nginx Proxy Manager
wss://url:8443/stream when if not port 443 I have an issue with the stream not responding
how can allow another port? **(if I use port 443 all works**)

**Comment by jmattheis** [comment]
Explain what you are trying to achieve. I don't understand what you mean.

**Comment by idanless** [comment]
I cannot open 443 from the router is already used
so i open 8433 
now the port use from WAN is 8433 -> 8443 Nginx {ssl}-> http screego i see error my chrome on WSS (
now I what I did i changed the ngnix be 443 -> http screego  (test by LAN all works)
this means something not working when this is not 443 

note: we are taking when you try to create a room before the stream  if you can give you a screenshot or you can change the ngnix be a listener to 8443 or any port, not 443 to see the issue (also by lan) https://lanipbindngnix:8443/

**Comment by jmattheis** [comment]
What's the error you are experiencing? What does stream not responding mean? What does screego log when the error occurs? Any log in the browser console?

**Comment by idanless** [comment]
basically timeout 
<img width="829" alt="image" src="https://github.com/user-attachments/assets/02c68967-297b-424b-92a5-0a7d00056814">
<img width="683" alt="image" src="https://github.com/user-attachments/assets/74180859-fb98-4f53-97a2-5e891783f00c">
as I said when this 443 (ngnix side) all works .. when isn't 443 the the issue appears

**Comment by jmattheis** [comment]
Could you enable debug logging by setting the environment variable `SCREEGO_LOG_LEVEL` to `debug`. Then restart screego, trigger the error and paste the log output here.
