### ISSUE TITLE
Cannot create room

### ISSUE THREAD

**Issue by ashishjullia** [screego/server#204]
It was working fine until yesterday but not anymore.

![image](https://github.com/user-attachments/assets/401370c6-de5d-4933-b848-941f5ef75e65)

![image](https://github.com/user-attachments/assets/ea9e8c93-3317-4f9f-bd6f-945f41b20ae6)

![image](https://github.com/user-attachments/assets/94408590-e267-43b2-9dfb-37d4a7457196)

**Comment by jmattheis** [comment]
Thanks for the report, should work for now, but I've to investigate what happened there.

**Comment by ashishjullia** [comment]
@jmattheis nope, not working, same thing, I've tried a couple of times throughout the day but same thing.

**Comment by jmattheis** [comment]
Yeah, it was unlucky, I only restarted the server and a couple hours it broke again.
![image](https://github.com/user-attachments/assets/ceaa84e7-043c-4391-acbe-1dbeb4eb69af)

I found the problem, it will be fixed in the next release which I'll release / deploy shortly.

**Comment by jmattheis** [comment]
Deployed a new version to https://app.screego.net, it should be fixed now, but reopen it it reoccurs for you.

**Comment by ashishjullia** [comment]
Seems to be working now, thanks for the quick fix, appreciate it @jmattheis
