### ISSUE TITLE
Screen Sharing Error "Could not play preview video AbortError"

### ISSUE THREAD

**Issue by Bristopher** [screego/server#207]
Currently when using NPM on the same network I can get the screen sharing to work _sometimes_, for some reason device1 (on same network as Screego) isn't able to stream and just streams a green screen to device2 but oddly device2 can stream to device1 just fine.

If I then try screen sharing on 2 different networks nothing gets displayed on the other device and the console outputs this error "Could not play preview video AbortError: The play() request was interrupted because the media was removed from the document." and on the device I'm sharing my screen in the mini preview window it shows I'm screen sharing a green screen.

I've port forwarded 3478 and 50000:50200 udp, enabled websocket support and force SSL in NPM, and have the docker setup below, got a feeling it has to do with the docker setup but I'm just not sure.

  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="CustomHostname"
  -e HOST_CONTAINERNAME="Screego"
  -e 'SCREEGO_EXTERNAL_IP'='dns:myDomainNameThatPointsToMyPublicIp'
  -e 'SCREEGO_TURN_PORT_RANGE'='50000:50200'
  -e 'SCREEGO_TRUST_PROXY_HEADERS'='true'
  -e 'SCREEGO_SERVER_ADDRESS'='0.0.0.0:5050'
  -e 'SCREEGO_TURN_ADDRESS'='0.0.0.0:3478'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:5050]'
  -l net.unraid.docker.icon='https://github.com/screego/server/blob/master/ui/src/logo.png?raw=true'
  -p '5050:5050/tcp'
  -p '3478:3478/tcp'
  -p '50000-50200:50000-50200/udp' 'screego/server:1'

**Comment by jmattheis** [comment]
Have you checked these steps? https://screego.net/#/faq?id=stream-doesnt-load

**Comment by Bristopher** [comment]
Yes, I've tried all extensions disabled, another browser, I'm using https, SCREEGO_EXTERNAL_IP is set, and I've portforwarded my router ports 3478-3478 tcp/udp, 50000-50200 udp, and NPM reverse proxy 5050.

**Comment by Bristopher** [comment]
> Have you checked these steps? https://screego.net/#/faq?id=stream-doesnt-load

Yes, I've tried all extensions disabled, another browser, I'm using https, SCREEGO_EXTERNAL_IP is set, and I've portforwarded my router ports 3478-3478 tcp/udp, 50000-50200 udp, and NPM reverse proxy 5050.

**Comment by jmattheis** [comment]
Does https://app.screego.net work for you?

**Comment by Bristopher** [comment]
Hmm on different networks on https://app.screego.net/ device1(home network) shares a green screen to device2, but when device2 screenshares it works but on device2 the preview window is green.

Also noticed my instance says "Nat Traversal via: [STUN]" Not sure why it's not using TURN like https://app.screego.net/

**Comment by jmattheis** [comment]
You need to configure users and login or change the `SCREEGO_AUTH_MODE` setting. The green screen is something wrong with your device / gpu drivers, nothing screego can do about this. You probably have the same problem when screen sharing via other websites.

**Comment by Bristopher** [comment]
That was it! I set SCREEGO_AUTH_MODE to none and it's now using TURN and works, thanks! 

You were right, I believe the green screen is due to the fact device2 is a Macbook running bootcamp windows and it green screens due to the gpu drivers.
