### ISSUE TITLE
Unable to start presentation getting error

### ISSUE THREAD

**Issue by santhoshvr** [screego/server#24]
i am getting **Uncaught (in promise) TypeError: navigator.mediaDevices is undefined** error in local server.

![image](https://user-images.githubusercontent.com/28789132/95574591-d1e16780-0a4a-11eb-94e1-7f1f9d6f739c.png)

![image](https://user-images.githubusercontent.com/28789132/95574612-df96ed00-0a4a-11eb-943b-461a24efa750.png)

Browser : Firefox version 81.0
OS: Ubuntu 18.04

**Comment by jmattheis** [comment]
Are you accessing the site through `localhost` or some ip?

**Comment by santhoshvr** [comment]
Sorry i am accessing using  IP not localhost.

If i accessed with localhost there is no error coming working fine.

But accessing through IP i am getting above error.

**Comment by santhoshvr** [comment]
For your reference:
![image](https://user-images.githubusercontent.com/28789132/95576436-128eb000-0a4e-11eb-8148-d4083448e267.png)

If i access through http://127.0.0.1:5050/ working fine :+1:  :)

But if i access through http://192.168.43.181:5050/ i am getting error in console.

Note: 
i have exported  `SCREEGO_EXTERNAL_IP="192.168.43.181"`.

**Comment by jmattheis** [comment]
See https://screego.net/#/config
> TLS is required for Screego to work. Either enable TLS inside Screego or use a reverse proxy to serve Screego via TLS.

**Comment by jmattheis** [comment]
I've added a better error message in https://github.com/screego/server/commit/c3c966dc00a57ec6e74326f15736f5a4864a3f9d.
