### ISSUE TITLE
Cancelling a presentation destroys the room you're in

### ISSUE THREAD

**Issue by whalehub** [screego/server#28]
### Steps to reproduce
1. Visit https://app.screego.net.
2. Click on the "Create room" button.
3. Click on the "Start presentation" button and select a screen.
4. Click on the "Cancel presentation" button.
5. Observe the room you're in getting destroyed.
6. See error message `malformed message: kekw unexpected end of JSON input` pop up in the browser.

### Environment
- **OS:** Windows 10
- **Browser:** Chromium 85 (no add-ons)

**Comment by jmattheis** [comment]
Good catch. I'll fix this shortly.

**Comment by jmattheis** [comment]
Fixed now (:.
