### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by BroderPeters** [screego/server#29]
For developers who are not so familiar with the used programming languages it would be nice to have a guide to "how to contribute" [like in this project](https://github.com/gotify/server/blob/master/CONTRIBUTING.md) (even tho gotify might be more complex) or like https://gotify.net/docs/dev-setup

Helpful steps might be:
* Needed local environments/frameworks
* build instructions
* test instructions

**Comment by jmattheis** [comment]
I've added something similar to dev-setup -> https://screego.net/#/development?id=build
