### ISSUE TITLE
Share Code Words

### ISSUE THREAD

**Issue by Rustymage** [screego/server#34]
Is the only way to join a session to share the link or manually type in the URL?

Can you not type in the three code words? Am I missing something?

**Comment by BroderPeters** [comment]
Right now I would say so. On the main page you can only create a room.

What would be the advantage of having to type in the words? If you are not able to share the link to someone (e.g. being on the phone)?

**Comment by Rustymage** [comment]
My use case would be with family members to assist in solving a problem that may not require control.

It'd be far quicker to say to head to example.com and enter x-y-z over having to copy the link, open an email client, email it, get them to login into email and click the link.

It eliminates some steps and was just my 2 cents :) 

Otherwise I'm keen to use this with family.

**Comment by Rustymage** [comment]
I'm going to close this as I don't think this needs further comment and it's just a feature idea.

👍
