### ISSUE TITLE
mac share to windows not work !!!!

### ISSUE THREAD

**Issue by Jamlee** [screego/server#36]
mac share to windows not work !!!!

**Comment by ajilk** [comment]
@Jamlee were you able to get it working on your mac? I am getting `turn: RelayAddress must be valid IP to use RelayAddressGeneratorStatic`

```
$ docker run --net=host --env-file env screego/server:1.0.5
2020-10-10T21:40:11Z DBG Logger initialized
2020-10-10T21:40:11Z INF SCREEGO_SECRET unset, user logins will be invalidated on restart
2020-10-10T21:40:11Z INF Users file not specified
2020-10-10T21:40:11Z FTL could not start turn server error="turn: RelayAddress must be valid IP to use RelayAddressGeneratorStatic"
```
```
$ cat env
SCREEGO_EXTERNAL_IP=0.0.0.0:4200
SCREEGO_SECRET=
SCREEGO_SERVER_TLS=false
SCREEGO_TLS_CERT_FILE=
SCREEGO_TLS_KEY_FILE=
SCREEGO_SERVER_ADDRESS=0.0.0.0:5050
SCREEGO_TURN_ADDRESS=0.0.0.0:3478
SCREEGO_TRUST_PROXY_HEADERS=false
SCREEGO_AUTH_MODE=none
SCREEGO_CORS_ALLOWED_ORIGINS=
SCREEGO_USERS_FILE=
SCREEGO_LOG_LEVEL=debug
SCREEGO_PROMETHEUS=false
```

**Comment by jmattheis** [comment]
@ajilk You need to put your real external ip in `SCREEGO_EXTERNAL_IP`.

**Comment by jmattheis** [comment]
@Jamlee Are you self hosting Screego or use the public instance?

**Comment by Jamlee** [comment]
@jmattheis i self hosting screego. below is command to start screengo.

```
docker run -d  --restart=always  -p 3478:3478 -p 5050:5050 -e SCREEGO_AUTH_MODE=none -e SCREEGO_EXTERNAL_IP=200.200.200.211 screego/server:1.0.5
```

mac share to mac is ok. win share to win, mac share to win is not worker for me. the chrome dev tools console have error. but it is not my pc, could not get the picture about error

**Comment by jmattheis** [comment]
@Jamlee try to use --net=host instead of explicit port bindings see https://screego.net/#/install
