### ISSUE TITLE
Great project 😀 

### ISSUE THREAD

**Issue by ProximaB** [screego/server#40]
It would be great if you add some credit about PION community without with it would have not be possible.

**Comment by whalehub** [comment]
@ProximaB It looks like screego is already listed here: https://github.com/pion/awesome-pion#media-api

**Comment by ProximaB** [comment]
Yup It has been added https://github.com/pion/awesome-pion/commit/71f71491a99137aa649ef2b9c4c476208519b27b
Thanks
