### ISSUE TITLE
Docker + Login to Screego

### ISSUE THREAD

**Issue by Silas-91** [screego/server#42]
Hi,

we are using screego in docker and it works good, but i want to user the "Login" option. 

Here is my docker-compose.yml. 

```bash
version: "3.7"
services:
    screego:
        image: screego/server:1.0.7
        network_mode: host
        volumes:
                - /root/screengo/screengo.passwd:/root/screengo.passwd
        environment:
            SCREEGO_EXTERNAL_IP: "X.X.X.X"
            SCREEGO_SECRET: "...................."
            SCREEGO_USERS_FILE: "/root/screengo.passwd"
            SCREEGO_LOG_LEVEL: "debug"
            SCREEGO_SERVER_ADDRESS: "screego.docker:5050"
            SCREEGO_TURN_ADDRESS: "X.X.X.X:3478"  
```
I understand that these settings should be correct.
When I start docker-compose and go to screego to test the login, I get this error message "Login Failed: could not authenticate". It seems that the user file will not be transferred. 

Does anyone have any advice how I can solve the problem?

**Comment by jmattheis** [comment]
Does screego output a log similar to this?
```
2020-10-20T10:55:10+02:00 INF Loaded Users amount=4
```
Has the usersfile a structure like this:
```
jmattheis:$2a$12$UXlgZUYoCh2jzoNs96GocOEToZ5Aa8d4pv13LzjTy.3gYSqoRq44a
other:$2a$12$/v3LA3YKao/ZpHtmZg8qKO7CPzwkTGKrAAYvfLt7jXdiVmjd0OzXK
```

**Comment by Silas-91** [comment]
I dont got the output like you have.

After further research, I found and solved the problem. the userfile was with MD5 and not with HASH. Sorry for the circumstances.

Thanks for your Help.
