### ISSUE TITLE
screengo is not working in private instance for Ubuntu 16.04

### ISSUE THREAD

**Issue by MadAboutProgramming** [screego/server#43]
While sharing the screen one pop-up should generate for which screen you want to share.That pop-up itself is not coming, so that screen share button is not working in my private instance.  I have checked the logs and there is no error message. 

sample screen I have attached for clarity.
![screenGoError](https://user-images.githubusercontent.com/50446730/96580619-2e1f7380-12f6-11eb-98e0-36c73e8fe970.png)

In public instances it's working. Let me know if anything requires configurations for private instances.

I have made the setup through docker.

~~~
version: "3.3"
services:
  screego:
    image: screego/server:1.0.7
    network_mode: host
    environment:
      SCREEGO_EXTERNAL_IP: "164.52.196.20"
~~~

Ubuntu : 16.04

**Comment by jmattheis** [comment]
Are you using https to connect to screego?

**Comment by MadAboutProgramming** [comment]
Noo.. Is it required https ?

**Comment by jmattheis** [comment]
Yes. See first line in https://screego.net/#/config

**Comment by MadAboutProgramming** [comment]
Ohh my bad. Thanks
