### ISSUE TITLE
WebSocket connection to 'wss://screen.injdk.cn/stream' failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by jiqing112** [screego/server#44]
I use binary screengo,built in the LAN,domain name is "screen.injdk.cn"

Use nginx reverse proxy screengo and configure SSL.

The domain name can be accessed or logged in, but when creating the room, It's a blank and the console gave me some http400 errors

Can I find a solution here?
Thank you for seeing my difficulties

![Snipaste_2020-10-22_17-27-01](https://user-images.githubusercontent.com/17674011/96852554-d581df00-148b-11eb-943c-28570a900b19.png)
![Snipaste_2020-10-22_17-32-13](https://user-images.githubusercontent.com/17674011/96853103-8b4d2d80-148c-11eb-84ff-b1fbfa4dfcdb.png)

![Snipaste_2020-10-22_17-24-40](https://user-images.githubusercontent.com/17674011/96852470-c00cb500-148b-11eb-9e11-0d26b1f24509.png)
![Snipaste_2020-10-22_17-26-11](https://user-images.githubusercontent.com/17674011/96852493-c307a580-148b-11eb-9722-4c9f0d5f35d5.png)
![Snipaste_2020-10-22_17-26-22](https://user-images.githubusercontent.com/17674011/96852497-c3a03c00-148b-11eb-86e1-48bab061226a.png)

**Comment by jmattheis** [comment]
Please post your nginx config.

**Comment by jiqing112** [comment]
> Please post your nginx config.
```

server
{
    listen 80;
	listen 443 ssl http2;
    server_name screen.injdk.cn;
    index index.php index.html index.htm default.php default.htm default.html;
    root /www/wwwroot/screen.injdk.cn;
    
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }

    ssl_certificate    /www/server/panel/vhost/cert/screen.injdk.cn/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/screen.injdk.cn/privkey.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    add_header Strict-Transport-Security "max-age=31536000";
    error_page 497  https://$host$request_uri;


    

    location ~ /purge(/.*) {
        proxy_cache_purge cache_one $host$1$is_args$args;
        #access_log  /www/wwwlogs/screen.injdk.cn_purge_cache.log;
    }
	include /www/server/panel/vhost/nginx/proxy/screen.injdk.cn/*.conf;

	include enable-php-00.conf;
    
    include /www/server/panel/vhost/rewrite/screen.injdk.cn.conf;
    
    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }
    
    #一键申请SSL证书验证目录相关设置
    location ~ \.well-known{
        allow all;
    }
    
    access_log  /www/wwwlogs/screen.injdk.cn.log;
    error_log  /www/wwwlogs/screen.injdk.cn.error.log;
}
```

```
#PROXY-START/
location  ~* \.(php|jsp|cgi|asp|aspx)$
{
    proxy_pass https://127.0.0.1:5050;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
}
location /
{
    proxy_pass https://127.0.0.1:5050;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    
    add_header X-Cache $upstream_cache_status;
    
    #Set Nginx Cache
    
    	add_header Cache-Control no-cache;
    expires 12h;
}

#PROXY-END/
```

**Comment by jmattheis** [comment]
The config misses the websocket proxy headers
```
proxy_set_header   Upgrade $http_upgrade;
proxy_set_header   Connection "upgrade";
proxy_redirect     http:// $scheme://;
```
https://screego.net/#/proxy?id=nginx

**Comment by jiqing112** [comment]
yes ,This is the correct solution，thank you for your reply

**Comment by jiqing112** [comment]
Is there a donation entrance? I invite you to have a coffee

**Comment by jiqing112** [comment]
Is there a donation entrance? I invite you to have a coffee

**Comment by jiqing112** [comment]
Look forward to your reply

**Comment by jmattheis** [comment]
@jiqing112 This is actually the first time that someone wants to donate. I'm honored (:. You can buy be a coffee through PayPal, here is the link [paypal.me/jmattheis](https://paypal.me/jmattheis)

**Comment by jiqing112** [comment]
> @jiqing112 This is actually the first time that someone wants to donate. I feel honored (:. You can buy be a coffee through PayPal, here is the link [paypal.me/jmattheis](https://paypal.me/jmattheis)

just a coffer，thanks for you open source and reply.

this is chinese night, I 'm go sleeping,

good night O(∩_∩)O

**Comment by jmattheis** [comment]
@jiqing112 Good night, thank you very much!
