### ISSUE TITLE
Using an external TURN server, i.e. Coturn

### ISSUE THREAD

**Issue by frittentheke** [screego/server#48]
Thank you for this cool application!

Would it be possible to allow Screego the use of an existing TURN server such as a Coturn (https://github.com/coturn/coturn) instance or even a public TURN server? Some installations might even make it hard to run / open the TURN server on the same machine.

**Comment by jmattheis** [comment]
This is certainly possible. I'd be open for PRs if someone wants to implement this.

**Comment by athoune** [comment]
OK, I try to do that : https://github.com/screego/server/pull/63

**Comment by athoune** [comment]
Hum, coturn handles lots of authentication backends.

I begin with hmac signature with timestamp, the easiest backend.

**Comment by maximbaz** [comment]
I'm not sure if we need to support all of them right away, maybe just pick one for now? I'm not too familiar with TURN but I've seen on other integrations people mostly use `static-auth-secret` (e.g. here in [Matrix](https://github.com/matrix-org/synapse/blob/develop/docs/turn-howto.md)).
