### ISSUE TITLE
Screenshare not working for public and private instances

### ISSUE THREAD

**Issue by YannickFricke** [screego/server#49]
Hey fellows,

at first: thanks for this awesome software! :heart: 

But I am getting the bug, that neither the public instance nor a private install with docker-compose have the screenshare working.

Sharing the screen is working but no one can see it (except if you open the same room in a private window on your own machine) (both instances (public + self-hosted))

There are no entries in the developer console nor in the output of the screego server where we could get a hint for the bug.

SSL is used for the private instance (with traefik on a .dev domain (which also only accepts SSL connections)).

I am using Chromium version 86.0.4240.111 for sharing the screen.

**Comment by jmattheis** [comment]
Did you verify all points on https://screego.net/#/faq?id=stream-doesnt-load ?

**Comment by YannickFricke** [comment]
Thanks for your response @jmattheis!

Yes I verified all points.

With the "public instance" I meant "https://app.screego.net/", so its not only happening on self hosted instances.

**Comment by jmattheis** [comment]
So you are sure, that you are using turn (this is not available on the public instance)? Have you tried different browsers?
