### ISSUE TITLE
Screego in Docker without nginx

### ISSUE THREAD

**Issue by Silas-91** [screego/server#50]
Hi all, 

i ´m actually using screego in docker with nginx, all in all it works fine.  
I have noticed that some users cannot share their screens. Now I want to try it out without nginx.
Now i would like to use screego in docker without nginx and now i have the problem that i can´t configure SSL. 

Do you have a solution for that? Do I have to use nginx for SSL? Or is this procedure not intended?

Thanks for your help.

**Comment by jmattheis** [comment]
See https://screego.net/#/config
```
# If TLS should be enabled for HTTP requests. Screego requires TLS,
# you either have to enable this setting or serve TLS via a reverse proxy.
SCREEGO_SERVER_TLS=false
# The TLS cert file (only needed if TLS is enabled)
SCREEGO_TLS_CERT_FILE=
# The TLS key file (only needed if TLS is enabled)
SCREEGO_TLS_KEY_FILE=
```
