### ISSUE TITLE
Screego inside local network?

### ISSUE THREAD

**Issue by merinleona** [screego/server#58]
i am currently trying to find a way to stream windows I have open on my Computer to my phone.
Now I could setup Screego on my external server, but it would be simpler if i could just install it on my Computer (which is a Linux PC so no problem there). my question is about all the config with external ip etc.. what do i put there if i only want to use it inside my own home network?

**Comment by jmattheis** [comment]
External ip doesn't mean public ip. You can put the ip from your private network in there. You can get it with `ip address`
In my case it would be 192.168.178.2
```
2: enp34s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:d8:61:c7:f9:2a brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.2/24 brd 192.168.178.255 scope global dynamic enp34s0
       valid_lft 846122sec preferred_lft 846122sec
```

**Comment by merinleona** [comment]
Thank you, I got stuck on external ip must be public ip. It is running very well now :)
