### ISSUE TITLE
Automatic fallback to TURN

### ISSUE THREAD

**Issue by maximbaz** [screego/server#61]
Hello, thanks so much for this project, it is amazing!

While learning about STUN and TURN I stumbled upon this quote from [Nextcloud docs](https://nextcloud-talk.readthedocs.io/en/turn_doc/TURN/):

> Nextcloud Talk will try direct P2P in the first place, use STUN if needed and TURN as last resort fallback. Thus to be most flexible and guarantee functionality of your Nextcloud Talk instance in all possible connection cases, you most properly want to setup a TURN server.

What do you think of implementing the same approach? We won't need to ask users to pick STUN or TURN before creating a room, it will always start as STUN, and only if connection cannot be established `screego` would automatically try TURN next.

Of course all the existing options should be respected, e.g. with `SCREEGO_AUTH_MODE=turn` the fallback to TURN would only happen if user is authenticated - exactly as it is today, I'm just thinking that we don't really have to ask users what they want, we can pick the best of the available options ourselves.

**Comment by jmattheis** [comment]
Hey @maximbaz,

Actually, Screego should already work like you describe it. The selection for TURN/STUN doesn't force the usage of it.
It only defines what can be used. This is defined by the WebRTC protocol.

> Typically, each peer will propose its best candidates first, making their way down the line toward their worse candidates.

https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Connectivity#ice_candidates

When you use something like https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ you can see which addresses are used:

Example for me (with turn active)
![image](https://user-images.githubusercontent.com/14895212/104022896-cf60ec00-51b8-11eb-8ada-79ff9cd8c819.png)

**Comment by maximbaz** [comment]
Wow, very interesting, thanks for explaining! Just to confirm, that selection box is only for informational purposes, and no matter what I select there, all the options will always be attempted? 

Is it possible to actually detect which protocol is used, or this is handled completely internally by WebRTC? Or if 5 people are present, for each of them it could be a separate protocol? I am just wondering if we can make this clearer, maybe by showing the currently used protocol inside the room, instead of during the creation of it 🤔

**Comment by jmattheis** [comment]
The selection box defines the upper bound.

If Stun is selected: Screego instructs WebRTC to use Local or Stun to establish a connection.
If Turn is selected: Screego instructs WebRTC to use Local, Stun or Turn to establish a connection.

> Is it possible to actually detect which protocol is used, or this is handled completely internally by WebRTC? 

It is probably possible to check this, but I'm not 100% sure.

> if 5 people are present, for each of them it could be a separate protocol?

Yeah, it is possible to have a user pair in a room which have a direct connection and another user pair which uses a relay to communicate.

> I am just wondering if we can make this clearer, maybe by showing the currently used protocol inside the room, instead of during the creation of it 

I'd find this interesting too, but I don't really think that it is useful, as it doesn't really change anything (:.

**Comment by maximbaz** [comment]
Makes sense! OK I have a final question and let's close this ticket, as my main question is already answered 🙂 Why not remove the select box and always use the upper bound as "Local, STUN, TURN"? If user is not authenticated and TURN requires auth, of course TURN will not be attempted anyway, right? Is there any other scenario where I would want to limit to STUN even if I have permission to use TURN?

**Comment by jmattheis** [comment]
Good question, I'd say my reasoning for this was to highlight what is used for Nat Traversal. It probably should be only a label and not a selection box.

**Comment by maximbaz** [comment]
And I agree 👍 Feel free to close this issue unless you want to keep it open as a reminder. Many thanks for your fast replies and explanation!

**Comment by jmattheis** [comment]
No problem, glad I could help (:
I've created an issue for the ux improvement.
