### ISSUE TITLE
Feature request: Start fullscreen mode by URL parameter

### ISSUE THREAD

**Issue by m23project** [screego/server#67]
Hi,

thank you for developing screego :-)

Could you please add an URL option that makes it possible to join a running screego session in fullscreen without clicking on the fullscreen button?

A complete URL (with login) could look like this: https://user:pass@example.com:12345/?room=room&fullscreen=true

Background: In OBS a browser element can be added to a scene. This browser opens an URL and is non-interactive. If you have a site (eg with screego) someone is streaming to, it can be embedded into OBS. This could be used to have screens shared by multiple praticipiants that are composed together into a scene and broadcasted.

Cu Hauke

**Comment by jmattheis** [comment]
Hey,

does OBS show the browser URL bar, or why does it have to be full screen? I don't think, that browsers allow starting a video in full screen without any user interaction as that would be pretty annoying if visit spam sites and such.

**Comment by m23project** [comment]
Hi,

OBS doesn't show an URL bar, but all UI elements that screego shows would be in the stream too. My intention is to have the raw desktop shared via screego without any additional UI elements. In fullscreen these elements are disapearing. Automatically running screego in fullscreen was the first idea I had.

But this is not allowed at least by Firefox and Chromium, I just figured out by creating a smal site that tries to go into fullscreen on loading. It seems that fullscreen requests need an user action and cannot be triggered by JavaScript alone. Maybe there is a workaround, but I didn't find one.

Next idea: Could you make the screego UI elements disappear by an URL parameter?

Cu Hauke

**Comment by jmattheis** [comment]
Yeah, this would be an option, but the elements should be hidden after some deloy, or does this not work when embedded into OBS?

**Comment by m23project** [comment]
Sorry for the delay. Seems that I get no eMail from github when there are messages waiting...

It should work in both ways. The best would be to hide the elements directly after the URL was opened. A short delay (1-2 seconds) would be ok too. A longer delay would make it more difficult to compose the scene in OBS, beause the final appearance would be shown too late and may need further adjustments of the scene (maybe cropping or moving of the browser).
