### ISSUE TITLE
Feature request: Share audio and webcam

### ISSUE THREAD

**Issue by m23project** [screego/server#68]
Hi,

could you make sharing of a webcam and microphone (in addition to screen sharing) available?

Cu Hauke

**Comment by BroderPeters** [comment]
I'm not a maintainer of this project, but some reasons why this probably won't come you can find here: https://github.com/screego/server/pull/66#issuecomment-763841571

**Comment by jmattheis** [comment]
As described in https://github.com/screego/server/pull/66#issuecomment-763841571, screego should stay as simple as possible. If you want something with more functionality use one of the options listed in https://github.com/screego/server/pull/66#issuecomment-763841571
