### ISSUE TITLE
BUG: Screenshare isn't stopped when using browser based "Stop sharing" button is clicked

### ISSUE THREAD

**Issue by DatMayo** [screego/server#69]
Hey,

in Google Chrome (and mabe other browsers) you have a "native" Button to stop your screen share. In german its called "Freigabe beenden" in English "Stop Share" (or simmilar).
![image](https://user-images.githubusercontent.com/1522607/106107345-1f432b00-6147-11eb-8b1a-386eef6a0ed7.png)

When pressing this button, the screen share window goes black and you need to click on "cancel presentation", to disable screen share.
![image](https://user-images.githubusercontent.com/1522607/106107573-603b3f80-6147-11eb-9873-21f2a84a67a3.png)

I think there is an event, which you can hook on to toggle this, without the need to click on "cancel presentation".

**Comment by jmattheis** [comment]
:+1:, if someone wants to contribute a fix, I'd be open to a PR.

**Comment by DatMayo** [comment]
I can try, but I've never worked with either go or react ;)
Can you tell me why your console.log(...) isnt shown when I start go with `go run . serve` and react page in ./ui with `npm run start`?

**Comment by jmattheis** [comment]
Which console.log? There are multiple.

**Comment by DatMayo** [comment]
@jmattheis Fixed it, thx to @YannickFricke.
If you have some spare time, feel free to check if its ok for you
