### ISSUE TITLE
Audio Streaming Support?

### ISSUE THREAD

**Issue by vascYT** [screego/server#81]
Will/Is there (be) audio streaming support?

**Comment by jmattheis** [comment]
No, see https://github.com/screego/server/issues/68

**Comment by vascYT** [comment]
Thanks

**Comment by L11R** [comment]
@vascYT I added audio sharing in my fork: https://github.com/L11R/screego
Should work.

**Comment by vascYT** [comment]
Ah thanks. I am not really familiar with go. How can I create a production binary file or can you send me an already built binary? I tried it with `go build`, but the thing is that I create a development binary file.

**Comment by L11R** [comment]
@vascYT I will try to prepare a release.

**Comment by vascYT** [comment]
Okay. Thanks a lot.

**Comment by L11R** [comment]
@vascYT please, check.

**Comment by vascYT** [comment]
Thanks a lot.

**Comment by vascYT** [comment]
Perfect. Thank you again.
