### ISSUE TITLE
Allow resolution / framerate selection

### ISSUE THREAD

**Issue by oxodao** [screego/server#84]
Hi!
This looks quite neat. Is there any plan to make a desktop client to stream the screen ?
That would be quite nice since the major problem for these kind of tool is the lack of ability to change resolution, for us having small connections it's laggy as heck..

It would be nice to be able to say "share x application at 480p" the same way it's possible on Discord

**Comment by jmattheis** [comment]
Hi, forcing a resolution would be possible with the current approach, there is no need for a separate application.

**Comment by oxodao** [comment]
Oh I thought it wouldn't. We're talking the upload side resolution, right ?
Like I'm sharing my screen at 480p meaning I will only upload 480p worth of content ? (even though having transcoding for choosing résolution at play time might be interesting too)

**Comment by jmattheis** [comment]
Yeah, the browser that captures the screen can define a resolution/framerate. https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#properties_of_video_tracks

**Comment by oxodao** [comment]
That's neat !

**Comment by DatMayo** [comment]
@jmattheis Are you allready working on it? Otherwise I'd like to have a look into it and try supporting your project :)

**Comment by jmattheis** [comment]
@DatMayo Nope, I'm not working on it. Feel free to implement it (:. Maybe a menu could be added to the triple dot button on the right side which opens a dialog with settings for resolution & framerate.

**Comment by DatMayo** [comment]
That was exactly, what I've thought :D I'll report back, when I have new informations

**Comment by jmattheis** [comment]
Framerate is configurable as of v1.9.1, however it currently only works when sharing in chrome, because firefox ignores the setting.

**Comment by jmattheis** [comment]
Limiting the resolution seems to be counterintuitive for the goal of screego (screensharing for developers). So I'll close this ticket as fixed, because the framerate is configurable.
