### ISSUE TITLE
Allow configuring a domain name instead of external ip

### ISSUE THREAD

**Issue by huseyin** [screego/server#89]
We are allowed to indicate the local IP of machine (e.g. `192.168.XX.XX`) by default. However, I noticed that we are not able to specify the external IP with `0.0.0.0`. `0.0.0.0` means to connect every available interfaces including the loopback as we all know and it is quite useful when it comes to floating IPs. Many of cloud providers tend not to set a public IP statically, which means it can be changed one day. Or, server might be hidden behind a load balancer. It would be great if you could include such a feature, therefore.

**Comment by jmattheis** [comment]
0.0.0.0 can be used when you want to listen on interfaces. This is already possible to define for the listen addresses:
```ini
# The address the http server will listen on.
SCREEGO_SERVER_ADDRESS=0.0.0.0:5050

# The address the TURN server will listen on.
SCREEGO_TURN_ADDRESS=0.0.0.0:3478
```
https://screego.net/#/config

The IP inside SCREEGO_EXTERNAL_IP will be transmitted to clients, thus it needs to be something specific that can be used outside the server that hosts screego. Technically it would be possible to define a domain there, but I don't see a real need for this.

**Comment by huseyin** [comment]
I didn't know the concept deeply. Thank you for informing @jmattheis Yeah my second question was that. It may need to solve the domain first and may bring some technical difficulties as you mentioned. I would want to have such a user experience anyway because of the reasons I featured in the issue.

**Comment by jmattheis** [comment]
Changed this to a feature request.
