### ISSUE TITLE
no stream available

### ISSUE THREAD

**Issue by zzx131** [screego/server#91]
hello , i use "./screego serve screego.config"  command start screego , but open browser find  "no stream available", can you tell me how start stream , help me ，thank you very much.

![11](https://user-images.githubusercontent.com/22722085/120597330-7c454980-c477-11eb-935e-27d72ed2e4da.png)

**Comment by jmattheis** [comment]
Hey, 

move your mouse and click the start stream button:
![image](https://user-images.githubusercontent.com/14895212/120601319-1393a800-c44a-11eb-9bb0-10d276d635e9.png)

**Comment by zzx131** [comment]
I'm sorry to disturb you again when I click "start presentation" browser tips 
"Could not start presentation. (mediaDevices undefined) Are you using https?" how to defined mediaDevices？thank you very much.

![22](https://user-images.githubusercontent.com/22722085/120751519-b592bd80-c53a-11eb-9361-340529a18203.png)

**Comment by zzx131** [comment]
i use https can use . thank you very much，You are a good man.
