### ISSUE TITLE
When one person starts sharing the screen, others in the room cannot click the share button

### ISSUE THREAD

**Issue by zzx131** [screego/server#92]

**Comment by jmattheis** [comment]
What do you mean with "cannot click", like the button missing / disabled?

**Comment by zzx131** [comment]
Thank you for you reply,i want to click  not show the sharing button, so I want to konw the status when someone is sharing the scree in the current room

**Comment by jmattheis** [comment]
These is a member list on the button menu, in there each user is displayed with a label when the user is streaming. Is this enough?
