### ISSUE TITLE
Latency measurements (e.g. compared to uStreamer)

### ISSUE THREAD

**Issue by dumblob** [screego/server#96]
Do you have any latency measurements somewhere? I'd be interested in comparison with [uStreamer](https://github.com/pikvm/ustreamer ).

**Comment by jmattheis** [comment]
Nope, I haven't done any latency tests with screego. Still they should be pretty good, as WebRTC (the web standard screego uses) was specifically designed for real-time kommunication, hence the name Web Real-Time Communication.

**Comment by dumblob** [comment]
Ok. From my experience with other "real time" solutions (KVM-like especially) the latency is higher (at least several hundreds of milliseconds for full HD resolution with 30 fps).

If nobody from the community is interested in estimating (or better measuring) the latency, then feel free to close this.
