### ISSUE TITLE
The mobile terminal cannot display the computer screen

### ISSUE THREAD

**Issue by wangdemon** [screego/server#99]
I use computers to create rooms and share computer screens，then use the iPhone and iPad to access the shared screen URL respectively. But neither the iPhone nor the iPad shows anything.Their screenshots are as follows:
1 Computer screen sharing
![1](https://user-images.githubusercontent.com/20681339/123518362-18a9e700-d6d8-11eb-9297-0f7a82f6e641.png)
2 iPhone access to shared screen URL
![2](https://user-images.githubusercontent.com/20681339/123518377-3414f200-d6d8-11eb-9928-c161fd0d1bc6.png)
3 iPad access to shared screen URL
![3](https://user-images.githubusercontent.com/20681339/123518386-3f681d80-d6d8-11eb-8a68-776c7c78d554.jpg)

**Comment by jmattheis** [comment]
https://screego.net/#/faq?id=stream-doesnt-load

**Comment by wangdemon** [comment]
When my other computers visit the shared screen URL, it can display shared screens.But I use Android phone to access the shared screen URL, and it can't be displayed.
![5](https://user-images.githubusercontent.com/20681339/123518890-953dc500-d6da-11eb-9401-dc452d3c9d37.png)

**Comment by wangdemon** [comment]
I also clicked Joined button, it didn't work

**Comment by jmattheis** [comment]
no stream available means, that there is no one that currently streams, you need to start the stream on app.screego.net.

**Comment by wangdemon** [comment]
I already started the stream, My other computer can already see the shared screen

**Comment by jmattheis** [comment]
Doesn't look like it on the android screenshot.

**Comment by jmattheis** [comment]
Does sharing work between android & pc with app.screego.net?

**Comment by wangdemon** [comment]
Yes,I want to access my computer desktop through my mobile phone

**Comment by wangdemon** [comment]
![6](https://user-images.githubusercontent.com/20681339/123519284-cc14da80-d6dc-11eb-8878-e004eccc69b0.jpg)

**Comment by jmattheis** [comment]
You say yes, but in your screenshot there is no shared screen on your phone. So, **does** it work on app.screego.net or not?

**Comment by wangdemon** [comment]
My computer already shows the shared screen, so it work on app.screego.net.

**Comment by jmattheis** [comment]
You probably have misconfigured screego, if everything does work on app.screego.net. Recheck your SCREEGO_EXTERNAL_IP setting, it should probably point to `192.168.1.5`. And be sure to access the same URL on your phone & browser.

I feel like you aren't really answering my questions, thus, I don't like to debug this anymore.
